name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
    types: [synchronize, opened, reopened, converted_to_draft, ready_for_review]

env:
  LLVM_MAJOR_VERSION: "18"
  RUST_VERSION: 1.85
  MACOSX_DEPLOYMENT_TARGET: '12.0'

jobs:
  ubuntu-test:
    name: Ubuntu Test
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt

      - name: Add LLVM deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{ env.LLVM_MAJOR_VERSION }} main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install LLVM
        run: |
          v=${{ env.LLVM_MAJOR_VERSION }}
          sudo apt-get install llvm-${v} llvm-${v}-dev llvm-${v}-runtime clang-${v} clang-tools-${v} lld-${v} libpolly-${v}-dev
          echo "LLVM_SYS_${v}0_PREFIX=/usr/lib/llvm-${v}/" >> $GITHUB_ENV
          echo "PATH=/usr/lib/llvm-${v}/bin:$PATH" >> $GITHUB_ENV

      - name: Install typos
        uses: taiki-e/install-action@typos
      - name: Check typos
        run: typos .
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-features --benches --examples --tests -- -D warnings
      - name: Run tests
        run: cargo test -r --workspace --all-features

  macos-test:
    name: Macos Test
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt
      - name: Install LLVM (brew)
        run: |
          v=${{ env.LLVM_MAJOR_VERSION }}
          brew install "llvm@${v}"
          echo "LLVM_SYS_${v}0_PREFIX=$(brew --prefix llvm@${v})" >> $GITHUB_ENV
          echo "PATH=$(brew --prefix)/opt/llvm@${v}/bin:$PATH" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/opt/homebrew/lib:$LIBRARY_PATH" >> $GITHUB_ENV
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-features --benches --examples --tests -- -D warnings
      - name: Run tests
        run: cargo test -r --workspace --all-features
